<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-UDJ5PR4" name="fengrao.Demo3" tests="18" failures="1" timestamp="3 Dec 2019 11:48:40 GMT" time="471.267" errors="0">
  <testcase name="test3" time="27.838" classname="fengrao.Demo3"/>
  <testcase name="test5" time="27.502" classname="fengrao.Demo3"/>
  <testcase name="test2" time="19.124" classname="fengrao.Demo3"/>
  <testcase name="test5" time="25.163" classname="fengrao.Demo3"/>
  <testcase name="test5" time="25.454" classname="fengrao.Demo3">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at fengrao.Demo3.test5(Demo3.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test5 -->
  <testcase name="test3" time="29.386" classname="fengrao.Demo3"/>
  <testcase name="test3" time="27.388" classname="fengrao.Demo3"/>
  <testcase name="test9" time="25.387" classname="fengrao.Demo3"/>
  <testcase name="test1" time="20.326" classname="fengrao.Demo3"/>
  <testcase name="test5" time="25.018" classname="fengrao.Demo3"/>
  <testcase name="test3" time="30.396" classname="fengrao.Demo3"/>
  <testcase name="test51" time="24.416" classname="fengrao.Demo3"/>
  <testcase name="test7" time="22.757" classname="fengrao.Demo3"/>
  <testcase name="test4" time="36.421" classname="fengrao.Demo3"/>
  <testcase name="test3" time="28.105" classname="fengrao.Demo3"/>
  <testcase name="test8" time="26.843" classname="fengrao.Demo3"/>
  <testcase name="test52" time="22.863" classname="fengrao.Demo3"/>
  <testcase name="test5" time="26.880" classname="fengrao.Demo3"/>
</testsuite> <!-- fengrao.Demo3 -->
